### ISSUE TITLE
Suggested section for the vignette re: F1000Research copy editing

### ISSUE THREAD

**Issue by mikelove** [grimbough/BiocWorkflowTools#4]
I just used BiocWorkflowTools to submit a workflow to F1000Research. Everything went smoothly (I uploaded the files manually out of preference). Thanks for your hard work!

One thing which I think might help others in the future, is if in the BiocWorkflowTools vignette you could mention that the F1000Research copy editors do not want undefined acronyms in the Figure or Table captions for workflow articles. The copy editors marked up every caption asking us to not use acronyms (even if these have been introduced already in the text) as they want each figure and table to stand alone. This information may be useful to others, as it can avoid people having to go back and edit two documents in parallel (the original source Rmd and the edited version of the latex output on Overleaf). 

Maybe this section could grow over time, also, as others encounter things like this that would be easy to fix earlier in the writing process, before submitting to F1000Research.

**Comment by grimbough** [comment]
Hi Mike, thanks for the feedback.  For now I've added some extra advice to the article skeleton, so anyone who creates a new article will see that alongside the document structure and R Markdown syntax guide.  The vignette needs a bit of work in the near future, so I'll try and add something there too.

When I submitted the meta-workflow the editor actually worked in the Rmd file, using the `<!-- TEXT -->` syntax to add comments.  That way I could clone the Rmd via git, work in it directly, regenerate the latex file and commit them both back.  It's a little circular, but required less copy/paste between documents.

**Comment by mikelove** [comment]
Thanks! Oh i didn't even think to ask them to edit the Rmd. That's a good point.

**Comment by CosmeSanchezMiguel** [comment]
Hello Mike, Thank you for creating this fantastic package, I am currently using your package for a project. I don’t intend to submit it to F1000Research. I have customised a few things in the .sty file (colours, footer, header, two columns, logo, etc.), but I wonder if there is an easy way to remove the blank space between the abstract and the introduction. Best regards.
